- name: common
  hosts: all
  roles:
    - role: roles/common
  tags:
    - common

- name: eeee
  hosts: all
  roles:
    - role: roles/eeee
  tags:
    - eeee

- name: umami
  hosts: all
  roles:
    - role: roles/umami
  tags:
    - umami

- name: oslf
  hosts: all
  roles:
    - role: roles/oslf
  tags:
    - oslf

- name: zipline
  hosts: all
  roles:
    - role: roles/zipline
  tags:
    - zipline

- name: plane
  hosts: all
  roles:
    - role: roles/plane
  tags:
    - plane

- name: gatus
  hosts: all
  roles:
    - role: roles/gatus
  tags:
    - gatus

- name: uptime-kuma
  hosts: all
  roles:
    - role: roles/uptime-kuma
  tags:
    - uptime-kuma

- name: n8n
  hosts: all
  roles:
    - role: roles/n8n
  tags:
    - n8n

- name: grist
  hosts: all
  roles:
    - role: roles/grist
  tags:
    - grist

- name: boardfsdash
  hosts: all
  roles:
    - role: roles/boardfsdash
  tags:
    - boardfsdash