- name: Ensure Secrets
  include_tasks:
    file: secrets.yml
    apply:
      tags:
        - zipline.secrets
  tags:
    - zipline.secrets

- name: Ensure Postgres Database
  include_tasks:
    file: postgres.yml
    apply:
      tags:
        - zipline.postgres
  tags:
    - zipline.postgres

- name: Deploy Web Application
  include_tasks:
    file: web.yml
    apply:
      tags:
        - zipline.web
  tags:
    - zipline.web
