image: quay-its.epfl.ch/svc0176/boardfsdash
version: 1.1
app: boardfsdash
subdomain: dash
secrets: "{{ lookup('pipe', 'keybase fs read /keybase/team/epfl_sopec/boardfsdash/secrets.yml') | from_yaml }}"
domain: fsd.epfl.ch